<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://cdn.bootcss.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <title>Hello, MOBILE!</title>
    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://cdn.bootcss.com/jquery/3.2.1/jquery.min.js" type="text/javascript"></script>
    <script type="text/javascript">
        $(function(){
            // 方案一
            $.getScript('http://sso.example3.com/login_api?scheme=1')

            // 方案二
            $.ajax({
                url: 'http://sso.example3.com/login_api?scheme=2',
                xhrFields: {
                    withCredentials: true
                },
                success: function(response) {
                    console.log(response)
                }
            })
        })
    </script>
</head>
<body>
<h1>Hello, Mobile!</h1>
</body>
</html>